### ISSUE TITLE
Output cells and location for gappa-tutorial.ipynb

### ISSUE THREAD

**Issue by cdeil** [libgamera/GAMERA#17]
@JoachimHahn Do you want to fix (see #15) and maintain the gappa-tutorial here?
https://github.com/gammapy/PyGamma15/blob/gh-pages/tutorials/gamera/gappa-tutorial.ipynb
Or do you want to move it to some other repo (e.g. GAMERA)?

In any case, I think it would be better if you have a version with output plots on Github or http://nbviewer.ipython.org/ , for people that want to just read it before installing GAMERA.

**Comment by JoachimHahn** [comment]
Closing old issues:
I have setup my own gh-pages directly linked to the GAMERA github page, but thanks for the offer!!
