### ISSUE TITLE
flux units mismatch in tutorials 1 and 2

### ISSUE THREAD

**Issue by sybenzvi** [libgamera/GAMERA#18]
Hi there: I've been playing with gamera a bit.  It's a nice package and is easy to install. But I noticed when running tutorials 1 and 2 that the units of E^2*Flux are coming out many orders of magnitude lower than in the same plots on your documentation page (http://joachimhahn.github.io/GAMERA/). When I switched from the master to the Astro branch and ran the tutorials, the units matched the documentation.

I'm not sure if the documentation is just out of synch with the main branch the or if there is a deeper issue. At first glance there doesn't seem to be some obvious explanation, like expressing energies in keV instead of erg.  Thanks!

**Comment by JoachimHahn** [comment]
Dear sybenzvl,

sorry for the late reply; I didn't notice the notification :(
Thanks for your interest in the package! Concerning your question:

Yes, the tutorial is out of date ... I really, really have to update it.
The reason  for the mismatch is that, after some user feedback, the input unit for 
distances changed from cm to pc (which is a more natural unit in astrophysics imo).

Thank you for pointing me to this, I will update the tutorial asap!

Cheers,
Joachim

**Comment by JoachimHahn** [comment]
Closing old issues:
I have set up a whole new tutorial page, linked on the github page. The tutorials there work. Thanks for your support, Joachim
