### ISSUE TITLE
Problem with C++11 libraries on OS X El Capitan 10.11

### ISSUE THREAD

**Issue by rlopezcoto** [libgamera/GAMERA#19]
Hi,

I cannot compile gappa on my mac using the Makefile provided. The problem is that when it calls python/setup.py, first of all it does not have any link to c++11 libraries and I get:

../src/Radiation.C:1561:3: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]

then, if I add the extra arguments to setup.py:
extra_compile_args.append('-std=c++11 -stdlib=libc++')

the compiler does not recognize the c++11 libraries and I get:
error: invalid value 'c++11 -stdlib=libc++' in '-std=c++11 -stdlib=libc++'

it is very weird, because if I copy in the command line the command that setup.py is trying to run, it works without any problem. I tried using exactly the same compiler inside setup.py as the one I use in the command line, but it still works for the command line and it does not work for setup.py.

**Comment by rlopezcoto** [comment]
@ParsonsRD I had forgotten about this. Instead of running
python setup.py

copy the full command line that setup.py is trying to run and it will work ;-)

**Comment by JoachimHahn** [comment]
Closing old issues:
Thanks for bringing this up. All the code that was specificly C++11 has been removed, so it should be no problem anymore.
