### ISSUE TITLE
Make python3 compatible

### ISSUE THREAD

**Issue by JoachimHahn** [libgamera/GAMERA#2]
# Swig does all the wrapping. Currently, the flags are

-python -c++ -py3 -nosafecstrings
## Running a python script with the package results in a crash, e.g.:

$ python3 docu/tutorial/TutorialLevel2.py docu/tutorial/TutorialLevel2Params.dat 
Traceback (most recent call last):
  File "docu/tutorial/TutorialLevel2.py", line 6, in <module>
    import gamerapy
  File "/home/joachim/Documents/Arbeit/GAMERAGIT/lib/gamerapy.py", line 28, in <module>
    _gamerapy = swig_import_helper()
  File "/home/joachim/Documents/Arbeit/GAMERAGIT/lib/gamerapy.py", line 24, in swig_import_helper
    _mod = imp.load_module('_gamerapy', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: /home/joachim/Documents/Arbeit/GAMERAGIT/lib/_gamerapy.so: undefined symbol: PyClass_Type

**Comment by JoachimHahn** [comment]
Had to remove the -py3 flag because with this it doesn't run with python2

**Comment by cdeil** [comment]
Python 3 would be great!

Most people are still on Python 2 (see http://astrofrog.github.io/blog/2015/05/09/2015-survey-results/), but that is changing quickly now that several Linuxes are starting to ship Python 3 by default and with Anaconda.

Let me know if you get stuck with this issue and I"ll have a look.

**Comment by cdeil** [comment]
My suggestion would be to bundle the six.py file and then use that to achieve Python 2 / 3 compatible source code:
https://pythonhosted.org/six/

E.g.

``` python
from gamerapy.extern.six.moves import ConfigParser
```

**Comment by JoachimHahn** [comment]
Closing all the old issues. 
GAMERA works with python3 for a while now.
