### ISSUE TITLE
Bug in the EnergyLossRate calculation

### ISSUE THREAD

**Issue by rlopezcoto** [libgamera/GAMERA#21]
The constants **bremsl_epf** and **bremsl_eef** are not initialize when calculating the energy losses with the function Particles::EnergyLossRate.
The problem is that they are initialized when calling the function **Particles::CalculateConstants()**, but the function is not called before the EnergyLossRate one.

The final wrong result I found so far is that the Bremsstrahlung losses are 0.

**Comment by JoachimHahn** [comment]
Closing old issues:
Thanks for the bug report - I fixed that a while ago but forgot to close this issue!
