### ISSUE TITLE
Add make help target?

### ISSUE THREAD

**Issue by cdeil** [libgamera/GAMERA#4]
How about adding a `make help` target that prints the available commands?
Example: https://github.com/cta-observatory/ctapipe/blob/master/Makefile#L3

Without this, one always has to read the Makefile to know what's available and what they targets do.
(IMO just `make` shouldn't build the docs, that should be left to `make docs`)

**Comment by JoachimHahn** [comment]
Good idea! 

Added

help:
    @echo ''
    @echo 'GAMERA available make targets:'
    @echo ''
    @echo '  gamera           Create the GAMERA shared object (lib/libgamera.so)'
    @echo '  gamerapy         Wrap the python module (lib/gamerapy.py and lib/_gamerapy.so)'
    @echo '  tutorial1        Compile a simple tutorial program'
    @echo '                   (-> bin/TutorialLevel1, see http://joachimhahn.github.io/GAMERA/)'
    @echo '  documentation    Generate documentation'
    @echo '                   (-> docu/doxygen/html/ and docu/sphinx/build/html/)'
    @echo '  clean            remove temporary files'

to the Makefile

**Comment by cdeil** [comment]
Thanks!

A `make install` would be great!
Usually people want to install a package and then just use it, without having to fiddle with `LD_LIBRARY_PATH`, `DYLD_LIBRARY_PATH` everytime they want to use it.

**Comment by cdeil** [comment]
Thanks!
