### ISSUE TITLE
make always rebuilds

### ISSUE THREAD

**Issue by cdeil** [libgamera/GAMERA#7]
For GAMERA, make doesn't behave like make, it always re-executed the commands.

Can you fix the Makefile to only rebuild where needed?
(It's not really important for such a small package, feel free to close the issue if you don't think it's worth it to declare dependencies within the Makefile correctly to make this work.)

**Comment by JoachimHahn** [comment]
Closing old issues:
As you say, this is a small package, so it doesn't hurt to clean and rebuild everything.
